sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk9

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18c65e29b9926a658da8
    on_success: always
    on_failure: always
    on_start: always
